export const AZURE_SERVICE_BUS_CONFIGURATION =
  'AZURE_SERVICE_BUS_CONFIGURATION';

export const AZURE_SERVICE_BUS_EVENT_SUBSCRIBER_CLIENT =
  'AZURE_SERVICE_BUS_EVENT_SUBSCRIBER_CLIENT';

export const AZURE_SERVICE_BUS_SUBSCRIBER = 'AZURE_SERVICE_BUS_SUBSCRIBER';
export const AZURE_SERVICE_BUS_SENDER = 'AZURE_SERVICE_BUS_SENDER_';
